path:
  data: /var/lib/elasticsearch
  logs: /var/log/elasticsearch

node:
  name: 0.0.0.0:9200
network:
  host: 127.0.0.1
cluster.name: ${LOG_HOST_NAME}

discovery.seed_hosts:
  - 127.0.0.1
discovery.seed_providers:
  - 127.0.0.1
cluster.initial_master_nodes:
  - master-node-a
  - master-node-b

xpack:
  security:
    enabled: false
    transport:
      ssl:
        enabled: false